research_task:
  description: |
    Use only the `wikipedia_search` and `wikipedia_fetch` tools to investigate the topic "{topic}".
    Provide 6–10 bullet points with verifiable facts (definitions, key people, dates, important terms).
    For each bullet, include in parentheses the corresponding Wikipedia URL(s).
    Do not include any external links.
  expected_output: |
    A list of 6–10 bullet points plus a "References (Wikipedia)" section containing only Wikipedia URLs.
  agent: researcher

writing_task:
  description: |
    Based solely on the researcher's findings, write a Markdown-formatted article including:
    - Title
    - TL;DR (3–5 sentences)
    - Introduction
    - 3–5 explanatory sections (H2)
    - Conclusion
    - "References (Wikipedia)" section containing only the same URLs provided by the researcher.
    Hard requirement: the article body (excluding the Title, TL;DR, headings, and the "References (Wikipedia)" section)
    must contain at least 300 words. If it is shorter, expand the content using only the research facts.
    Do not add or reference any external links.
  expected_output: |
    A complete Markdown article ready to publish, referencing only Wikipedia pages, with a body of at least 300 words.
  agent: writer
  context:
    - research_task

editing_task:
  description: |
    Review the draft for clarity, grammar, cohesion, and factual alignment with the information obtained from Wikipedia.
    Make sure the final version includes only the same Wikipedia references provided by the researcher.
    Verify the article body (excluding the Title, TL;DR, headings, and the "References (Wikipedia)" section) has at least 300 words.
    If it does not, expand the text to meet this minimum while remaining faithful to the research.
    Deliver a polished Markdown file.
  expected_output: |
    The final, edited Markdown article, clean and professional, with only Wikipedia references and a body of at least 300 words.
  agent: editor
  context:
    - writing_task

reporting_task:
  description: >
    Revise os achados, estruture como relatório e finalize.
  expected_output: >
    Um relatório em Markdown, com título, resumo, achados, seções e referências.
  agent: writer
  markdown: true          # ← a doc permite usar markdown no YAML
  output_file: report.md  # ← mantém o .md no root
