research_task:
  description: |
    Use only the `wikipedia_search` and `wikipedia_fetch` tools to investigate the topic "{topic}".
    Provide 6–10 bullet points with verifiable facts (definitions, key people, dates, important terms).
    For each bullet, include in parentheses the corresponding Wikipedia URL(s).
    Do not include any external links.
  expected_output: |
    A list of 6–10 bullet points plus a "References (Wikipedia)" section containing only Wikipedia URLs.
  agent: researcher

writing_task:
  description: |
    Based solely on the researcher's findings, write a Markdown-formatted article including:
    - Title
    - TL;DR (3–5 sentences)
    - Introduction
    - 3–5 explanatory sections (H2)
    - Conclusion
    - "References (Wikipedia)" section containing only the same URLs provided by the researcher.
    Do not add or reference any external links.
  expected_output: |
    A complete Markdown article ready to publish, referencing only Wikipedia pages.
  agent: writer
  context:
    - research_task

editing_task:
  description: |
    Review the draft for clarity, grammar, cohesion, and factual alignment with the information obtained from Wikipedia.
    Make sure the final version includes only Wikipedia references.
    Deliver a polished Markdown file.
  expected_output: |
    The final, edited Markdown article, clean and professional, with only Wikipedia references.
  agent: editor
  context:
    - writing_task
