research_task:
  description: |
    Use ONLY the tools `wikipedia_search` and `wikipedia_fetch` (MediaWiki Action API) to investigate the topic: "{topic}".
    Goals:
      - Produce 6–10 bullet points with verifiable facts (definitions, key people, dates, terms).
      - After each bullet, include the exact Wikipedia canonical URL(s) from the tools in parentheses.
      - No speculation. No external links.
    Tool rules:
      - Call ONE tool per step.
      - On the 'Action:' line, write EXACTLY one of: wikipedia_search, wikipedia_fetch.
      - Do NOT add anything after the tool name (no '(multiple times)', 'First', numbering, or comments).
      - If you no longer need a tool, do NOT write 'Action:'; move to the final output.
    Output rules:
      - Return clear bullets with URLs in parentheses. No JSON needed for this step.

writing_task:
  description: |
    Using ONLY the researcher’s bullets and URLs, write the article and RETURN ONLY a JSON object (no extra text).
    Requirements:
      - Body length (sum of all sections.content_md) MUST be ≥ 300 words; use clear, consistent Markdown.
      - Provide 3–5 H2 sections that match the research focus.
      - References: ONLY Wikipedia URLs that appeared in the research bullets.
      - Language: if "{language}" is provided, write accordingly; otherwise default to English.
      - Style: active voice; short sentences; define terms on first use; avoid hedging/hype.
      - Your response MUST be valid JSON that conforms to ArticleDraft.
    expected_output: |
      JSON matching ArticleDraft

fact_check_task:
  description: |
    Verify the writer’s JSON article against the EXACT Wikipedia URLs using ONLY `wikipedia_search` and `wikipedia_fetch`.
    For each section, check claims for support/contradictions; propose minimal edits when needed.
    Instructions:
      - Use only the allowed tools. No external links.
      - Quote short claim snippets to pinpoint the issue; keep quotes ≤ 25 words.
      - If fully supported, mark "supported". If not present, "missing_citation". If contradicted, "contradicted".
      - Return ONLY JSON conforming to FactCheckReport (no prose).
    expected_output: |
      JSON matching FactCheckReport

editing_task:
  description: |
    Apply the fact-check fixes, ensure style/grammar/flow, and return the final JSON article.
    Rules:
      - Keep ONLY Wikipedia references used in research/writing.
      - Ensure ≥ 300 words total and clean Markdown.
      - Return ONLY a valid JSON object matching ArticleDraft (no extra text).
    expected_output: |
      JSON matching ArticleDraft
