research_task:
  description: |
    Use the `wikipedia_search` tool to investigate the topic "{topic}".
    Produce 6–10 concise bullet points with verifiable facts, including definitions,
    key names, dates, and brief explanations. Include the Wikipedia page URL and up to
    3–5 external links returned by the tool.
  expected_output: >
    A bullet list (6–10 items) plus a "References" section with the collected URLs.
  agent: researcher

writing_task:
  description: |
    Using the research findings, write a blog post in Markdown:
    - Title
    - TL;DR (3–5 lines)
    - Introduction
    - 3–5 H2 sections with clear, helpful explanations
    - Final considerations
    - "References" section containing the links provided by the researcher
  expected_output: >
    A clear and well-structured blog post in Markdown, suitable for publication.
  agent: writer
  context:
    - research_task

editing_task:
  description: |
    Revise the draft for clarity, cohesion, grammar and light SEO (headings, keywords).
    Ensure consistency with the research facts. Deliver the final Markdown version.
  expected_output: >
    A polished final Markdown article ready to publish.
  agent: editor
  context:
    - writing_task
